project_name: gomtastsflare
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: gomtastsflare
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
brews:
  - name: gomtastsflare
    tap:
      owner: stenstromen
      name: homebrew-tap
    commit_author:
      name: stenstromen
    folder: Formula
    homepage: https://github.com/Stenstromen/gomtastsflare
    description: Go binary for creating/updating MTA-STS records on Cloudflare, and create the accompanying Nginx configuration.